### ISSUE TITLE
Overlap examples issues

### ISSUE THREAD

**Issue by pnanez** [pnanez/HyEQ_Toolbox#37]
Update the Overlap examples and generate new figures. Those examples do not run properly

**Comment by pwintz** [comment]
I was able to run the examples in Example_1.8-A_Simple_Example without problem. You must navigate in to the subdirectories before running the initialization scripts.

**Comment by pwintz** [comment]
I'm closing this because the examples are running fine. We'll do cleanup, rewriting, and regenerating figures as a part of our broader efforts to clean up the examples and convert them from TeX to .m files.
