### ISSUE TITLE
Test/Update CPS examples from Coursera Course and write documentation

### ISSUE THREAD

**Issue by pnanez** [pnanez/HyEQ_Toolbox#43]
Include the new CPS examples, 
1) save those as 2012a slx, 
2) test if they compile in 2017b
    yes? go to 4)
    if not, run the update advisor, and apply the changes
3) repeat 1)
4) generate a tex file with a description of the example

**Comment by pwintz** [comment]
Where are these examples found/described?

**Comment by pwintz** [comment]
The documentation should be based on the martial at [the CPS Coursera Course](https://www.coursera.org/learn/cyber-physical-systems-1).
We have the following examples that need documentation: 
![image](https://user-images.githubusercontent.com/19618780/152433073-123bd09a-67ed-4ee5-9e0c-464243109b96.png)

**Comment by pwintz** [comment]
I talked to Ricardo about what format the new documentation should be in. He wants us to use MATLAB files published with the "publish" feature to generate HTML.

**Comment by pwintz** [comment]
Finished! (With help From Ryan, Adeel, Santiago, and Nan.)
