### ISSUE TITLE
draw function in simulink masks not supported for 2018 and up

### ISSUE THREAD

**Issue by pnanez** [pnanez/HyEQ_Toolbox#50]
the masks generate warnings due to the use of a draw function that is no longer needed/supported in the newer versions of matlab, we need to figure out if we want to keep it or how we can remove it without affecting previous versions

**Comment by pwintz** [comment]
I've run a few tests to see if there is a measurable difference between using `image('Hcal.jpg')` vs. `image(imread('Hcal.jpg'))`. There appears to be no difference in speed. Both work fine on the MATLAB versions we support in v3.0, so I am updating the masks for the Simulink blocks to omit `imread`.
