### ISSUE TITLE
Stop time parameter in newer simulink 

### ISSUE THREAD

**Issue by pnanez** [pnanez/HyEQ_Toolbox#52]
This is a new warning that I am getting in 2020. Every time that you drag a hybrid system block to a model this warning appears:

Warning: Error evaluating '' callback of SubSystem block (mask) 'untitled/HSu1'.
Callback string is 'set_param(gcb,'LinkStatus','none'),
set_param(gcs, 'MaxStep', 'MaxStep', 'RelTol', 'RelTol','Stop time', 'T')' 
Warning: block_diagram does not have a parameter named 'Stop time' 

It seems that the "Stop time" parameter changed its name or behavior. This might be problematic for backward compatibility.

I remember that we added in the callback "CopyFcn" the functionality of setting the MaxStep, RelTol, and Stop time to the model being created. This was nice because all of the examples/models had the same variable names linked to those Simulink parameters. This is useful when you are working in hybrid systems examples and models exclusively, but it is a pain when you are using those blocks in a general setting. For example, you can have your model working (that does not include HS blocks), and you already set up MaxStep, RelTol, and Stop time. Then you copy one of our blocks, and just for that, you override your previous configuration. I think that the entire feature must go. What are your thoughts @sjimen28 @HybridSystemsLab ?

**Comment by pwintz** [comment]
Fixing the warning was easy to do. I simply removed the space in "Stop Time". We can consider modifying the CopyFnc callback more, but this particular bug is fixed so I'm going to close this issue.
