### ISSUE TITLE
A minor terminological issue in the comments in run_bouncing_ball.m (gravitational acceleration vs gravity constant).

### ISSUE THREAD

**Issue by hurak** [pnanez/HyEQ_Toolbox#81]
This is a minor terminological issue. In the example `run_bouncing_ball.m` the line 13 reads:
> sys.gamma = 3.72; % gravity constant

I dare to recommend keeping the more standard terminology such as [gravitational acceleration](https://en.wikipedia.org/wiki/Gravitational_acceleration) instead of "gravity constant", because the latter sounds more like [gravitational constant](https://en.wikipedia.org/wiki/Gravitational_constant), which is a different quantity. After all, the very definition of the `BouncingBall` class in the equally named file does use the more appropriate terminology "acceleration due to gravity".

Just a minor issue, indeed.

**Comment by pwintz** [comment]
Hi @hurak, 

Thanks for bringing this up; I agree entirely. The "gravity constant" terminology is a holdover from v2.04. We updated it to "acceleration due to gravity" in some places in v3.0, as you noted, but I apparently missed several occurrences. I'll search through and fix the rest.
