### ISSUE TITLE
2 questions about the Fireflies example

### ISSUE THREAD

**Issue by hurak** [pnanez/HyEQ_Toolbox#84]
## AND/OR in the definition of the Flow set
In the documentation for the Fireflies Example, the formula for the flow set C says that tau1 must be in the interval [0,1] AND tau2 must be in the interval [0,1] too. But then the code (from the perspective of one firefly the tau variable of the other firefly enters as an input) reads 
```
if ((tau > 0) && (tau < 1)) || ((u > 0) && (u <= 1))  % flow condition
        inC = 1;  % report flow
```
which obviously contains OR instead of AND for presence of the two taus in their respective flow intervals. How come? Surprisingly, the code returns the anticipated behaviour. I must be overlooking something trivial here.

By the way, whatever is the answer, wouldn't it be more consistent to replace `(tau < 1)` with `(tau <= 1)`? I am now referring to the code snippet appearing in the documentation `Example 2: Synchronization of Two Fireflies`. In the Matlab m-file it is consistent.

## Third branch in the jump map
What is the role of the third branch/case in the definition of the jump map below?
```
function tauplus = g(tau, u, e)
    % Jump map for firefly.
    if (1+e)*tau < 1
        tauplus = (1+e)*tau;
    elseif (1+e)*tau >= 1
        tauplus = 0;
    else
        tauplus = tau;   
    end
end
```
The value of `(1+e)*tau` is either strictly less or greater than 1, therefore the third option here will never be applied, will it?

**Comment by pwintz** [comment]
> ## AND/OR in the definition of the Flow set
> In the documentation for the Fireflies Example, the formula for the flow set C says that tau1 must be in the interval [0,1] AND tau2 must be in the interval [0,1] too. But then the code (from the perspective of one firefly the tau variable of the other firefly enters as an input) reads
> 
> ```
> if ((tau > 0) && (tau < 1)) || ((u > 0) && (u <= 1))  % flow condition
>         inC = 1;  % report flow
> ```
> 
> which obviously contains OR instead of AND for presence of the two taus in their respective flow intervals. How come? Surprisingly, the code returns the anticipated behaviour. I must be overlooking something trivial here.

You are right that the flow condition should use `&&` instead of `||`. The reason it works is because `||` results in a larger flow set 
 `C` but is the system is using jump priority, so jumps are mainly determined by the jump set `D`. In fact, if you replace the flow set function with 
```
function inC  = C(tau, u) 
    inC = 1;  % always flow unless jump set indicates a jump
end
```
then the system still behaves the same way. Nevertheless, the Simulink model should match what we describe in the document, so I'll update it when I have some time.

> By the way, whatever is the answer, wouldn't it be more consistent to replace `(tau < 1)` with `(tau <= 1)`? I am now referring to the code snippet appearing in the documentation `Example 2: Synchronization of Two Fireflies`. In the Matlab m-file it is consistent.

Yes, you are right. Those code snippets are extracted from the Simulink model when we package the Toolbox, so we need to modify the model to fix the snippets.

> 
> ## Third branch in the jump map
> What is the role of the third branch/case in the definition of the jump map below?
> 
> ```
> function tauplus = g(tau, u, e)
>     % Jump map for firefly.
>     if (1+e)*tau < 1
>         tauplus = (1+e)*tau;
>     elseif (1+e)*tau >= 1
>         tauplus = 0;
>     else
>         tauplus = tau;   
>     end
> end
> ```
> 
> The value of `(1+e)*tau` is either strictly less or greater than 1, therefore the third option here will never be applied, will it?

Yes, that's right. The third branch is superfluous and should be removed.
